name: Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Проверка содержимого папки (для диагностики)
      - name: List files
        run: ls -la Lab1Bower/src/

      # Переход в папку с исходниками
      - name: Navigate to source directory
        run: cd Lab1Bower/src

      # Компиляция и сборка JAR (с абсолютными путями)
      - name: Compile and package
        run: |
          cd Lab1Bower/src
          javac -d ./out ./Game.java ./Arrow.java ./GamePanel.java ./GameThread.java ./Target.java
          jar cvfe Game.jar Game -C ./out .

      # Загрузка артефакта (исправленный путь)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SniperGame.jar
          path: Lab1Bower/src/Game.jar
