name: Build and Package

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: |
          cd Lab1Bower/src
          javac -d ./out Game.java Arrow.java GamePanel.java GameThread.java Target.java
          jar cvfe Game.jar Game -C ./out .

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Game.jar
          path: Lab1Bower/src/Game.jar

  build_portable:
    needs: build_jar
    runs-on: windows-latest
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: Game.jar

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install WiX (требуется для сборки)
        run: choco install wixtoolset -y

      - name: Generate Portable App
        run: |
          jpackage `
            --name SniperGame `
            --input . `
            --main-jar Game.jar `
            --main-class Game `
            --type app-image `
            --dest C:\dist `
            --win-console


      - name: Upload Portable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SniperGame-Portable.exe
          path: ./dist/SniperGame.exe
