name: Build and Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка Java (версия 17 рекомендуется для Swing)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Сборка проекта через javac (если нет Maven/Gradle)
      - name: Build JAR
        run: |
          cd Lab1Bower
          javac -d ./out ./src/*.java
          jar cvfe game.jar Game -C ./out .

      # Загрузка JAR-файла как артефакт
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game.jar
          path: game.jar
